apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-storage-pv
spec:
  capacity:
    storage: 1Gi
  # volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    # path: /mnt/data
    path: /var/lib/mysql
  # persistentVolumeReclaimPolicy: Recycle
  storageClassName: own
  # mountOptions:
  #   - hard
  #   - nfsvers=4.1
  # nfs:
  #   path: /tmp
  #   server: 172.17.0.2
