apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-storage-pvc
spec:
  storageClassName: own
  resources:
    requests:
      storage: 1Gi
  # volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
