# 定义mysql的Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webook-mysql-dev
spec:
  selector:
    matchLabels:
      app: webook-mysql-dev
  template:
    metadata:
      labels:
        app: webook-mysql-dev
    spec:
      containers:
      - image: mysql:8.0
        name: mysql-8
        env:
        - name: MYSQL_ROOT_PASSWORD
          # 如果你不想使用secret对象保存mysql登录密码，可以直接使用下面的方式指定，简单粗暴未尝不可    
          value: root
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
        ports:
        - containerPort: 3306
          name: mysql
        volumeMounts:
        - name: mysqlvolume
          mountPath: /var/lib/mysql
      volumes:
      - name: mysqlvolume
        # 使用pvc
        persistentVolumeClaim:
          claimName: mysql-pvc
---
#定义mysql的Service
apiVersion: v1
kind: Service
metadata:
  name: webook-mysql-dev
spec:
  selector:
    app: webook-mysql-dev
  type: NodePort
  ports:
  - port: 3306
    protocol: TCP
    targetPort: 3306
    nodePort: 31234

---

# 定义持久卷信息
apiVersion: v1
kind: PersistentVolume
metadata:
  # pv是没有namespace属性的，它是一种跨namespace的共享资源
  name: mysql-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  # 存储类，具有相同存储类名称的pv和pvc才能进行绑定
  storageClassName: manual
  hostPath:
    path: /mnt/data

  # nfs:
  #   path: /nfs/data/01
  #   server: 192.168.59.110
---
# 定义mysql的持久卷声明信息
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  # 存储类，具有相同存储类名称的pv和pvc才能进行绑定
  storageClassName: manual