# 定义持久卷信息
apiVersion: v1
kind: PersistentVolume
metadata:
  # pv是没有namespace属性的，它是一种跨namespace的共享资源
  name: pv-1gi
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  # 存储类，具有相同存储类名称的pv和pvc才能进行绑定
  storageClassName: nfs
  hostPath:
    path: /mnt/data

  # nfs:
  #   path: /nfs/data/01
  #   server: 192.168.59.110
---
# 定义mysql的持久卷声明信息
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  namespace: dev
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  # 存储类，具有相同存储类名称的pv和pvc才能进行绑定
  storageClassName: nfs