// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"example/wb/internal/repository"
	"example/wb/internal/repository/cache"
	"example/wb/internal/repository/dao"
	"example/wb/internal/service"
	"example/wb/internal/web"
	"example/wb/internal/web/jwt"
	"example/wb/ioc"
	"github.com/gin-gonic/gin"
)

import (
	_ "github.com/spf13/viper/remote"
)

// Injectors from wire.go:

func InitWebServer() *gin.Engine {
	cmdable := ioc.InitRedis()
	handler := jwt.NewJwtHandler(cmdable)
	logger := ioc.InitLogger()
	v := ioc.InitGinMiddlewares(cmdable, handler, logger)
	db := ioc.InitDB()
	userDao := dao.NewUserDao(db)
	userCache := cache.NewUserCache(cmdable)
	userRepository := repository.NewCachedUserRepository(userDao, userCache)
	userService := service.NewUserService(userRepository)
	freecacheCache := ioc.InitFreeCache()
	codeCache := cache.NewCodeLocalCache(freecacheCache)
	codeRepository := repository.NewCachedCodeRepository(codeCache)
	asyncSmsDao := dao.NewSmsDao(db)
	asyncSmsRepository := repository.NewAsyncSMSRepository(asyncSmsDao)
	smsService := ioc.InitSMSService(cmdable, asyncSmsRepository)
	codeService := service.NewCodeService(codeRepository, smsService)
	userHandler := web.NewUserHandler(userService, handler, logger, codeService)
	wechatService := ioc.InitWechatService()
	oAuth2WechatHandler := web.NewOAuth2WechatHandler(wechatService, handler, logger, userService)
	engine := ioc.InitWebServer(v, userHandler, oAuth2WechatHandler)
	return engine
}
